name: Pint

on: pull_request

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@latest
        with:
          preset: laravel
          verboseMode: true

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style: run Pint"
